package org.example.mapper;

import org.example.model.Drink;

public interface DrinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.DRINK
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.DRINK
     *
     * @mbg.generated
     */
    int insert(Drink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.DRINK
     *
     * @mbg.generated
     */
    int insertSelective(Drink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.DRINK
     *
     * @mbg.generated
     */
    Drink selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.DRINK
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Drink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.DRINK
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Drink record);
}