package org.example.mapper;

import org.example.model.Test1;

public interface Test1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.TEST1
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String test1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.TEST1
     *
     * @mbg.generated
     */
    int insert(Test1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.TEST1
     *
     * @mbg.generated
     */
    int insertSelective(Test1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.TEST1
     *
     * @mbg.generated
     */
    Test1 selectByPrimaryKey(String test1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.TEST1
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Test1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.TEST1
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Test1 record);
}